server:
    port: 8804

spring:
    datasource:
        url: jdbc:mysql://localhost/hawk?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
        username: root
        password: 123456
    jpa:
        show-sql: true
eureka:
    instance:
        hostname: localhost
    client:
        serviceUrl:
            defaultZone: http://localhost:8080/eureka/
