spring:
    datasource:
        url: jdbc:mysql://192.168.24.207:27437/hawk?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: root
        password: root

eureka:
    instance:
        ip-address: 127.0.0.1
    client:
        serviceUrl:
            defaultZone: http://localhost:8080/eureka/
server:
    port: 8086

hawk:
    prometheus:
        host: http://192.168.24.207:30090
        max-measurement-count: 100
