name: sonar
on:
  push:
    branches:
      - master
  pull_request:
      types: [ opened, synchronize, reopened ]
jobs:
  build:
    name: sonar-build-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      -   name: Build
          run: ./mvnw -B clean install
