server:
    port: 8803

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/hawk?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: root
        password: 123456
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
    redis:
        host: localhost

eureka:
    instance:
        hostname: localhost
    client:
        serviceUrl:
            defaultZone: http://localhost:8080/eureka/
        registry-fetch-interval-seconds: 5
hawk:
    container:
        default-instance-namespace: default
        domain-host: hawk.cn
        build-namespace: build
        app-image-prefix: "registry.cn-beijing.aliyuncs.com/9fbank/"
        gateway-url: "localhost:8001"
        pvc-log: true
    runtime:
        nginx:
            runtime:
                appImage: registry.cn-beijing.aliyuncs.com/9fbank/onecard_nginx:v3.0
                dataImage: registry.cn-beijing.aliyuncs.com/9fbank/onecard_init_npm:v3.0
                podInteractionVolume: /tmp/app:/usr/local/openresty/nginx/html
            build:
                npm:
                    image: registry.cn-beijing.aliyuncs.com/9fbank/onecard_npm_build:v3.0.5
                    volume: ""
                    mountPath: ""
        tomcat:
            runtime:
                appImage: registry.cn-beijing.aliyuncs.com/9fbank/onecard_tomcat8:v3.0.7
                dataImage: registry.cn-beijing.aliyuncs.com/9fbank/onecard_init_tomcat:v3.0
                podInteractionVolume: /tmp/app:/usr/local/apache-tomcat-8.5.46/webapps/ROOT
            build:
                npm:
                    image: registry.cn-beijing.aliyuncs.com/9fbank/onecard_tomcat_build:v3.0.9
                    volume: maven-repository-nfs
                    mountPath: /root/.m2/
        springboot:
            runtime:
                appImage: registry.cn-beijing.aliyuncs.com/9fbank/onecard_springboot8:v3.0.7
                dataImage: registry.cn-beijing.aliyuncs.com/9fbank/onecard_init_springboot:v3.0
                podInteractionVolume: /tmp/app:/app/jar
            build:
                maven:
                    image: registry.cn-qingdao.aliyuncs.com/kangta123/hawk/hawk_springboot_build:v4.0.1
                    volume: maven-repository-nfs
                    mountPath: /root/.m2/
                gradle:
                    image: registry.cn-qingdao.aliyuncs.com/kangta123/hawk/hawk_gradle_build:v4.0
                    volume: gradle-repository-nfs
                    mountPath: /gradle
